export const UI_TEXT = {
  fr: {
    nav: {
      projects: "Projets",
      skills: "Compétences",
      about: "À propos",
      contact: "Contact",
    },
    headerCta: "Me contacter",
    heroMeta: {
      role: "Développeur Fullstack Junior",
      location: "France",
    },
    heroTitle: "Fullstack junior.",
    heroSubtitle: "Prêt pour mon premier poste.",
    heroProjectsCta: "Voir mes projets",
    configHint:
      "Configuration: les liens et textes (email, GitHub, projets) sont dans",
    sections: {
      projects: { kicker: "Sélection", title: "Projets en cours" },
      skills: { kicker: "Focus", title: "Compétences" },
      about: { kicker: "Méthode", title: "À propos" },
      contact: { kicker: "Discutons", title: "Contact" },
    },
    about: {
      valueTitle: "Ce que j’apporte",
      valueBody:
        "J’aime transformer une idée en une application lisible, rapide et robuste. Je sors de formation et je cherche un poste junior fullstack pour grandir sur des projets concrets.",
      cvExtract: "Extrait de mon CV",
      resumeTitle: "Parcours (CV)",
      education: "Formation",
      experience: "Expérience",
      languages: "Langues",
      cvMissing: "Les données du CV n’ont pas pu être chargées. Le fichier",
      cvMissingSuffix: "est requis.",
    },
    contact: {
      availabilityTitle: "Disponible pour missions",
      availabilityBody:
        "Je cherche actuellement un poste de développeur fullstack junior. Je suis joignable par email, et mon CV ainsi que ma lettre de motivation sont disponibles au téléchargement.",
      phoneLabel: "Téléphone",
      addressLabel: "Adresse",
      emailCta: "Envoyer un email",
      downloadCv: "Télécharger le CV",
      downloadCoverLetter: "Télécharger la lettre",
      draftEmail: "Préparer un email",
      form: {
        name: "Nom",
        namePlaceholder: "Nom",
        message: "Message",
        messagePlaceholder: "Décrire le projet (besoin, délais, stack…)",
        subjectPrefix: "Contact portfolio — ",
        subjectFallback: "Nouveau message",
      },
    },
    footerBackToTop: "Retour en haut ↑",
    footerRights: "Tous droits réservés.",
    langToggle: {
      toEnglish: "EN",
      toFrench: "FR",
      titleToEnglish: "English",
      titleToFrench: "Français",
      ariaToEnglish: "Switch language to English",
      ariaToFrench: "Passer la langue en français",
    },
  },
  en: {
    nav: {
      projects: "Projects",
      skills: "Skills",
      about: "About",
      contact: "Contact",
    },
    headerCta: "Contact",
    heroMeta: {
      role: "Junior full-stack developer",
      location: "France",
    },
    heroTitle: "Junior full-stack.",
    heroSubtitle: "Ready for my first role.",
    heroProjectsCta: "View projects",
    configHint: "Config: links and text (email, GitHub, projects) are in",
    sections: {
      projects: { kicker: "Selected", title: "Ongoing projects" },
      skills: { kicker: "Focus", title: "Skills" },
      about: { kicker: "Approach", title: "About" },
      contact: { kicker: "Let’s talk", title: "Contact" },
    },
    about: {
      valueTitle: "What I bring",
      valueBody:
        "I enjoy turning an idea into a readable, fast and robust application. I’m finishing my training and looking for a junior full-stack role to grow on real-world projects.",
      cvExtract: "From my resume",
      resumeTitle: "Resume",
      education: "Education",
      experience: "Experience",
      languages: "Languages",
      cvMissing: "Resume data could not be loaded. The file",
      cvMissingSuffix: "is required.",
    },
    contact: {
      availabilityTitle: "Available",
      availabilityBody:
        "I’m currently looking for a junior full-stack developer role. Email is available, and my CV and cover letter can be downloaded.",
      phoneLabel: "Phone",
      addressLabel: "Address",
      emailCta: "Email",
      downloadCv: "Download CV",
      downloadCoverLetter: "Download cover letter",
      draftEmail: "Draft email",
      form: {
        name: "Name",
        namePlaceholder: "Name",
        message: "Message",
        messagePlaceholder: "Describe the project (needs, timeline, stack…)",
        subjectPrefix: "Portfolio contact — ",
        subjectFallback: "New message",
      },
    },
    footerBackToTop: "Back to top ↑",
    footerRights: "All rights reserved.",
    langToggle: {
      toEnglish: "EN",
      toFrench: "FR",
      titleToEnglish: "English",
      titleToFrench: "Français",
      ariaToEnglish: "Switch language to English",
      ariaToFrench: "Switch language to French",
    },
  },
};
